---
title: "Using the package locally"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{local_use}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Installing and loading the package

```{r setup, results='hide', warning = FALSE, message = FALSE}
# # Installing
# install.packages("devtools")
# devtools::install_github("BencePalfi/SampleSizeBF")
# 
# # Loading
# library(SampleSizeBF)
```

# Samplesize planning

You can plan your sample size TODO add more explanation

## Normal prior

TODO add more explanation

```{r}
Bf_samplesize(distribution_likelihood = "normal", distribution_prior = "normal", sd_of_theory = 1.5, sd1 = 1.8, sd2 = NULL, tail = 1, threshold = 3, tpr = .8, n_start = 5, n_end = 1000, step = 1)
```

## Cauchy prior

TODO add more explanation

```{r}
Bf_samplesize(distribution_likelihood = "normal", distribution_prior = "cauchy", sd_of_theory = 1.5, sd1 = 1.8, sd2 = NULL, tail = 1, threshold = 3, tpr = .8, n_start = 5, n_end = 1000, step = 1)
```

## Uniform prior

TODO add more explanation

```{r}
Bf_samplesize(distribution_likelihood = "normal", distribution_prior = "uniform", sd_of_theory = 1.5, sd1 = 1.8, sd2 = NULL, tail = 1, threshold = 3, tpr = .8, n_start = 5, n_end = 1000, step = 1)
```


